# Generated by Django 2.2.3 on 2019-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemonelementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElementType', verbose_name='стихии'),
        ),
    ]
