# Generated by Django 2.2.3 on 2019-08-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElementType', verbose_name='силён против'),
        ),
    ]
