# Generated by Django 2.2.3 on 2019-08-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'покемон', 'verbose_name_plural': 'покемоны'},
        ),
        migrations.AlterModelOptions(
            name='pokemonelementtype',
            options={'verbose_name': 'стихия', 'verbose_name_plural': 'стихии'},
        ),
        migrations.AlterModelOptions(
            name='pokemonentity',
            options={'verbose_name': 'экземпляр покемона', 'verbose_name_plural': 'экземпляры покемонов'},
        ),
    ]
