# Generated by Django 2.2.3 on 2019-08-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20190802_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='element_type',
            new_name='element_types',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.Pokemon', verbose_name='из кого эволюционировал'),
        ),
    ]
